### ISSUE TITLE
Inconsistent sample number in meta analysis post

### ISSUE THREAD

**Issue by daniel-wells** [mvuorre/blog-academic#1]
In your meta analysis post the example using metafor uses 16 samples:
https://github.com/mvuorre/blog-academic/blob/b77678af5ed5172aa0c3afc117fc1f9f69ffac39/content/post/2016-09-29-bayesian-meta-analysis.html#L213
But the brms example has only 15:
https://github.com/mvuorre/blog-academic/blob/b77678af5ed5172aa0c3afc117fc1f9f69ffac39/content/post/2016-09-29-bayesian-meta-analysis.html#L254-L255

I believe this results in an estimate that's too low:
https://github.com/mvuorre/blog-academic/blob/b77678af5ed5172aa0c3afc117fc1f9f69ffac39/content/post/2016-09-29-bayesian-meta-analysis.html#L264-L266
The metafor estimate is higher and the CI doesn't overlap 0:
https://github.com/mvuorre/blog-academic/blob/b77678af5ed5172aa0c3afc117fc1f9f69ffac39/content/post/2016-09-29-bayesian-meta-analysis.html#L228-L229

The sd(Intercept) is also showing as almost double the metafor estimate:
https://github.com/mvuorre/blog-academic/blob/b77678af5ed5172aa0c3afc117fc1f9f69ffac39/content/post/2016-09-29-bayesian-meta-analysis.html#L259-L262
https://github.com/mvuorre/blog-academic/blob/b77678af5ed5172aa0c3afc117fc1f9f69ffac39/content/post/2016-09-29-bayesian-meta-analysis.html#L219

When I run your code myself I get a result much more consistent with metafor:
```
Group-Level Effects: 
~study (Number of levels: 16) 
              Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
sd(Intercept)     0.10      0.04     0.04     0.19       1274 1.00

Population-Level Effects: 
          Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
Intercept     0.15      0.04     0.08     0.22       1749 1.00
```

So perhaps something went wrong during the generation of the html file?

Someone else also got confused by this: https://discourse.mc-stan.org/t/brms-multivariate-meta-analysis-syntax/6801/3

**Comment by mvuorre** [comment]
Thank you very much for this. I've noticed that many of the blog posts have been garbled one way or the other. It's got something to do with how blogdown behaves quite unpredictably. When I get some time I will change the platform and will also make sure that bugs like this will be removed.

Thanks
Matti

**Comment by mvuorre** [comment]
Fixed with a redirect to new blog
